name: "Game Arena"
slug: "gamearena"
version: "1.0.2"
description: "Game Arena - Kotlin KMP backend + Compose Wasm frontend"
arch:
  - amd64
  - aarch64
ports:
  8080/tcp: 8080
map:
  - type: addon_config
    read_only: false
    path: /data
init: false
