name: "Game Arena"
slug: "gamearena"
version: "v1.1.1"
description: "Game Arena - Kotlin KMP backend + Compose Wasm frontend"
arch:
  - amd64
  - aarch64
image: "ghcr.io/kotucz/game-arena"
ports:
  8080/tcp: 6433
map:
  - app_config:rw
init: false
