gamearena {
  port = 8080

  web-root = "../app/webApp/build/dist/wasmJs/productionExecutable"

  database-path = "data/gamearena.db"

  admin {
    username = "admin"
    password = "supersecret"
  }

  firebase {
    googleCredentialsPath = "firebase.json"
  }
}
